import java.time.LocalDate;
import java.util.Arrays;

/**
 * Write a description of class Driver here.
 * Daljeet Singh 3169763
 * 5th November, 2024
 */

public class Driver {
    public static void main(String[] args) {
        // A list of all Canadian Prime Ministers with their "election dates"
        // (Note: Not all of these PMs were actually elected, but these are the dates they took office)
        // Generated by GPT
        PrimeMinister[] pms = {
                new PrimeMinister("Alexander", "Mackenzie", new LocalDate[]{
                        LocalDate.of(1873, 5, 2)  // May 2, 1873
                    }),
                new PrimeMinister("Sir John", "Thompson", new LocalDate[]{
                        LocalDate.of(1892, 10, 5) // October 5, 1892
                    }),
                new PrimeMinister("Sir John", "Abbott", new LocalDate[]{
                        LocalDate.of(1891, 5, 16) // May 16, 1891
                    }),
                new PrimeMinister("Sir Mackenzie", "Bowell", new LocalDate[]{
                        LocalDate.of(1895, 12, 21) // December 21, 1895
                    }),
                new PrimeMinister("Sir Charles", "Tupper", new LocalDate[]{
                        LocalDate.of(1896, 5, 1) // May 1, 1896
                    }),
                new PrimeMinister("Sir Wilfrid", "Laurier", new LocalDate[]{
                        LocalDate.of(1896, 6, 6), // June 6, 1896
                        LocalDate.of(1900, 3, 27) // March 27, 1900
                    }),
                new PrimeMinister("Robert", "Borden", new LocalDate[]{
                        LocalDate.of(1911, 10, 10), // October 10, 1911
                        LocalDate.of(1915, 10, 24) // October 24, 1915
                    }),
                new PrimeMinister("Arthur", "Meighen", new LocalDate[]{
                        LocalDate.of(1920, 7, 10), // July 10, 1920
                        LocalDate.of(1921, 6, 29) // June 29, 1921
                    }),
                new PrimeMinister("William Lyon Mackenzie", "King", new LocalDate[]{
                        LocalDate.of(1921, 9, 6), // September 6, 1921
                        LocalDate.of(1925, 1, 1), // January 1, 1925
                        LocalDate.of(1935, 1, 30) // January 30, 1935
                    }),
                new PrimeMinister("Richard B.", "Bennett", new LocalDate[]{
                        LocalDate.of(1930, 10, 7) // October 7, 1930
                    }),
                new PrimeMinister("Louis", "St. Laurent", new LocalDate[]{
                        LocalDate.of(1943, 11, 15) // November 15, 1943
                    }),
                new PrimeMinister("Jean", "Chrétien", new LocalDate[]{
                        LocalDate.of(1993, 10, 25), // October 25, 1993
                        LocalDate.of(1997, 6, 2), // June 2, 1997
                        LocalDate.of(2000, 11, 27) // November 27, 2000
                    }),
                new PrimeMinister("John", "Diefenbaker", new LocalDate[]{
                        LocalDate.of(1957, 3, 31), // March 31, 1957
                        LocalDate.of(1959, 6, 18) // June 18, 1959
                    }),
                new PrimeMinister("Lester B.", "Pearson", new LocalDate[]{
                        LocalDate.of(1963, 4, 22), // April 22, 1963
                        LocalDate.of(1965, 4, 20) // April 20, 1965
                    }),
                new PrimeMinister("Pierre", "Trudeau", new LocalDate[]{
                        LocalDate.of(1968, 4, 20), // April 20, 1968
                        LocalDate.of(1980, 2, 18), // February 18, 1980
                        LocalDate.of(1984, 6, 30) // June 30, 1984
                    }),
                new PrimeMinister("Joe", "Clark", new LocalDate[]{
                        LocalDate.of(1979, 6, 4) // June 4, 1979
                    }),
                new PrimeMinister("John", "Turner", new LocalDate[]{
                        LocalDate.of(1984, 8, 3) // August 3, 1984
                    }),
                new PrimeMinister("Stephen", "Harper", new LocalDate[]{
                        LocalDate.of(2006, 1, 23), // January 23, 2006
                        LocalDate.of(2008, 10, 14), // October 14, 2008
                        LocalDate.of(2011, 5, 2) // May 2, 2011
                    }),
                new PrimeMinister("Justin", "Trudeau", new LocalDate[]{
                        LocalDate.of(2015, 10, 19), // October 19, 2015
                        LocalDate.of(2019, 10, 21), // October 21, 2019
                        LocalDate.of(2021, 9, 20) // September 20, 2021
                    }),
                new PrimeMinister("Brian", "Mulroney", new LocalDate[]{
                        LocalDate.of(1984, 6, 30), // June 30, 1984
                        LocalDate.of(1988, 11, 21) // November 21, 1988
                    }),
                new PrimeMinister("Kim", "Campbell", new LocalDate[]{
                        LocalDate.of(1993, 6, 25) // June 25, 1993
                    }),
                new PrimeMinister("Paul", "Martin", new LocalDate[]{
                        LocalDate.of(2003, 12, 12) // December 12, 2003
                    }),
                new PrimeMinister("Sir John A.", "Macdonald", new LocalDate[]{
                        LocalDate.of(1867, 7, 1), // July 1, 1867
                        LocalDate.of(1873, 5, 2)  // May 2, 1873
                    })
            };

        System.out.println("Unsorted: ");
        for(PrimeMinister pm : pms){
            System.out.println("\t" + pm);
        }

        Arrays.sort(pms);

        System.out.println("Natural Sorted: ");
        for(PrimeMinister pmss: pms){
            System.out.println("\t" + pmss);
        }
    
        for (int i = 0; i < pms.length - 1; i++) {
            for (int j = 0; j < pms.length - i - 1; j++) {
                if (pms[j].getRecent().compareTo(pms[j + 1].getRecent()) < 0) {
                    PrimeMinister PM = pms[j];
                    pms[j] = pms[j + 1];
                    pms[j + 1] = PM;
                }
            }
        }
        
        System.out.println("5 most recently elected PM:");
        for (int i = 0; i < 5 && i < pms.length; i++) {
            System.out.println("\t" + pms[i]);
        }
        
        for (int i = 0; i < pms.length - 1; i++) {
            for (int j = 0; j < pms.length - i - 1; j++) {
                int lastName = pms[j].getLastName().compareTo(pms[j + 1].getLastName());
                if (lastName > 0 || (lastName == 0 && pms[j].getFirstName().compareTo(pms[j + 1].getFirstName()) > 0)) {
                    PrimeMinister PM = pms[j];
                    pms[j] = pms[j + 1];
                    pms[j + 1] = PM;
                }
            }
        }

        System.out.println("Alphabetical before 1900:");
        for (PrimeMinister pm : pms) {
            if (pm.getRecent().getYear() < 1900) {
                System.out.println("\t" + pm);
            }
        }
    }
}