def rotate_letter(letter: str, n: int) -> str:
    """
    Rotates a single letter by a given number of positions in the alphabet.
    """
    if letter.isupper():
        start = ord('A')
    else:
        start = ord('a')

    offset = ord(letter) - start
    new_offset = (offset + n) % 26 + start
    return chr(new_offset)

def rotate_string(word: str, n: int) -> str:
    """
    Rotates each letter in a string by a given number of positions in the alphabet.
    """
    result = ''
    for letter in word:
        result += rotate_letter(letter, n)
    return result

def make_word_dict():
    """
    Read the words in words.txt and return a dictionary
    that contains the words as keys
    """
    word_dict = dict()
    file_in = open('words.txt')
    for line in file_in:
        word = line.strip().lower()
        word_dict[word] = None
    return word_dict

def rotate_pairs(word, word_dict):
    """
    Prints all words that can be generated by rotating word.

    word: string
    word_dict: dictionary with words as keys
    """
    for i in range(1, 14):
        rotated = rotate_string(word, i)
        if rotated in word_dict:
            print(word, i, rotated)

if __name__ == '__main__':
    dictionary = make_word_dict()

    for word in dictionary:
        rotate_pairs(word, dictionary)

def test_rotate_letter():
    """
    Tests the rotate_letter function.
    """
    assert rotate_letter('A', 1) == 'B'
    assert rotate_letter('a', 1) == 'b'
    assert rotate_letter('Z', 3) == 'C'
    assert rotate_letter('z', 3) == 'c'
    assert rotate_letter('x', 5) == 'c'

def test_rotate_string():
    """
    Tests the rotate_string function.
    """
    assert rotate_string("cheer", 7) == "jolly"
    assert rotate_string("melon", -10) == "cubed"
    assert not rotate_string("HAL", -1) == "IBM"

def test_make_word_dict():
    """
    Tests the make_word_dict function.
    """
    word_dict = make_word_dict()
    assert 'hello' in word_dict
    assert 'world' in word_dict
